# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1

# Use Node LTS Alpine as base image
FROM node:lts-alpine AS builder

# Set working directory
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src

RUN npm ci && npm run build

# Runtime image
FROM node:lts-alpine
WORKDIR /app

# Copy built artifacts and dependencies
COPY --from=builder /app/package.json /app/package-lock.json ./
COPY --from=builder /app/dist ./dist

# Install only production dependencies
RUN npm ci --omit=dev

# Default command
CMD ["node", "dist/server.js"]
